# Generated by Django 3.2.14 on 2022-07-05 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('interest', models.FloatField()),
                ('value', models.FloatField()),
                ('full_value', models.FloatField()),
                ('comission', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('installments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.installment')),
            ],
        ),
    ]
