# Generated by Django 3.2.14 on 2022-07-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate_table',
            name='installments',
        ),
        migrations.AddField(
            model_name='rate_table',
            name='installments',
            field=models.ManyToManyField(to='loan.Installment'),
        ),
    ]
