# Generated by Django 3.2.12 on 2022-07-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratetable',
            name='installments',
        ),
        migrations.AddField(
            model_name='ratetable',
            name='installment',
            field=models.ManyToManyField(related_name='installment', to='loan.Installment'),
        ),
    ]
